### ISSUE TITLE
Old moderated posts are received and shown instead of the recent one

### ISSUE THREAD

**Issue by espoem** [wehmoen/utopian.reviews#3]
#### Expected behavior

When a user clicks the name of a moderator, the list of received posts should be from the most recent and should be deterministic.

![image.png](https://res.cloudinary.com/hpiynhbhq/image/upload/v1515889034/mjvqfx50cxuct5yp8ang.png)

#### Actual behavior

Clicking repeatedly on the name of the same moderator will show old and not uptodate list of moderated posts.

![image.png](https://res.cloudinary.com/hpiynhbhq/image/upload/v1515889104/jsge2ksxytscbrcida5d.png)

#### How to reproduce

1. Sign in https://utopian.reviews (be a Utopian supervisor)
2. Click on one moderator repeatedly

* Browser:  Google Chrome 63.0.3239.108
* Operating system: Windows 10

#### Recording Of The Bug

![ezgif.com-video-to-gif.gif](https://res.cloudinary.com/hpiynhbhq/image/upload/v1515889494/nezjja1tgy3h4pqyz78v.gif)   

<br /><hr/><em>Posted on <a href="https://utopian.io/utopian-io/@espoem/old-moderated-posts-are-received-and-shown-instead-of-the-recent-one">Utopian.io -  Rewarding Open Source Contributors</a></em><hr/>

**Comment by wehmoen** [comment]
Thanks for the report. Should be fixed with the latest commits!
